### ISSUE TITLE
TypeError: TextIOWrapper.write() takes exactly one argument (0 given)

### ISSUE THREAD

**Issue by linzinha** [linzinha/rotating_rotator#4]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1885, in __call__
    return self.func(*args)
  File "/Users/xxxxxxxxx/Documents/rotating_rotator/keygen.py", line 20, in saveNumKey
    g.write()
TypeError: TextIOWrapper.write() takes exactly one argument (0 given)

**Comment by linzinha** [comment]
This doesn't seem to happen anymore
