### ISSUE TITLE
New position key doesn't write

### ISSUE THREAD

**Issue by linzinha** [linzinha/rotating_rotator#7]
Likely an issue with default_position_key variable when writing as opposed to selecting a key

**Comment by linzinha** [comment]
Position key writes, doesn't encrypt

Traceback (most recent call last):
  File "/Users/xxxxxx/Documents/rotating_rotator/rotating_rotator.py", line 148, in <module>
    lock_file()
  File "/Users/xxxxxxx/Documents/rotating_rotator/rotating_rotator.py", line 99, in lock_file
    with open(active_fernet_key, 'rb') as mykey:
FileNotFoundError: [Errno 2] No such file or directory: FERNET KEY TEXT'

**Comment by linzinha** [comment]
Position key encrypts
